# Generated by Django 2.2.24 on 2022-04-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filr',
            name='base_url_filr',
            field=models.URLField(default='https://transfert.loire-atlantique.fr/', help_text="URL de base de l'API Filr (example: https://transfert.loire-atlantique.fr/)", verbose_name='URL API Filr'),
        ),
    ]
